spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 1000

  druid:
    aop-patterns: com.atguigu.admin.*  #监控Spring这个包下的所有组件
    filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

    stat-view-servlet:        # 配置监控页功能
      enabled: true           # 配置开启监控页
      login-username: admin
      login-password: admin
      resetEnable: false      #是否有重置按钮

    web-stat-filter:  # 监控web
      enabled: true           #开启监控web
      urlPattern: /*          #过滤路径
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


    filter:    #开启单个filter
      stat:    # 对上面filters里面的stat的详细配置
        slow-sql-millis: 1000   #超过1000毫秒的查询都是慢查询
        logSlowSql: true        #是否记录慢查询
        enabled: true           #开启功能
      wall:
        enabled: true           #开启功能
        config:
          drop-table-allow: false #防火墙拦截删表操作

#配置mybatis的规则
mybatis:
#  config-location: classpath:mybaits/mybatis-config.xml    #指定mybatis全局配置文件的位置
  mapper-locations: classpath:mybatis/mapper/*.xml         #sql映射文件位置
  #    注意事项，一旦配置了configuration，就相当于了config-location，这两个不能一起使用
  configuration:
    map-underscore-to-camel-case: true   #开启驼峰命名

